/*
  Innhold til Lynrunden og minirundene. Legg gjerne til flere.
*/

// Lynrunden: åpne spørsmål som besvares muntlig. Fasiten vises for hosten.
const LYN_QUESTIONS = [
  { q: "Hva heter Norges kronprins?", a: "Haakon" },
  { q: "Hvor mange ben har et insekt?", a: "6" },
  { q: "Hva er hovedstaden i Spania?", a: "Madrid" },
  { q: "Hvilket år gikk Titanic ned?", a: "1912" },
  { q: "Hva heter verdens høyeste fjell?", a: "Mount Everest" },
  { q: "Hvor mange minutter er det i en time?", a: "60" },
  { q: "Hvilken farge har en sjiraffs tunge?", a: "Blålilla / mørk blå" },
  { q: "Hva heter hovedpersonen i «Zelda»-spillene?", a: "Link" },
  { q: "Hvilket land vant Eurovision i 2023?", a: "Sverige (Loreen)" },
  { q: "Hva kalles en baby-kenguru?", a: "Joey" },
  { q: "Hvor mange strenger har en vanlig gitar?", a: "6" },
  { q: "Hvilket grunnstoff har symbolet O?", a: "Oksygen" },
  { q: "Hva heter Donald Ducks tre nevøer?", a: "Ole, Dole og Doffen" },
  { q: "Hva er 7 ganger 8?", a: "56" },
  { q: "Hva er Norges nasjonaldag?", a: "17. mai" },
  { q: "Hva heter den største byen i Nord-Norge?", a: "Tromsø" },
  { q: "Hvem skrev «Harry Potter»?", a: "J.K. Rowling" },
  { q: "Hva heter den lengste elven i verden (vanlig svar)?", a: "Nilen" },
  { q: "Hvor mange kontinenter er det?", a: "7" },
  { q: "Hva heter Mikke Mus' hund?", a: "Pluto" },
  { q: "Hvilket instrument spilte Ole Bull?", a: "Fiolin" },
  { q: "Hva heter det største landet i verden?", a: "Russland" },
  { q: "Hvor mange spillere er det på et volleyballag på banen?", a: "6" },
  { q: "Hva er det kjemiske symbolet for jern?", a: "Fe" },
  { q: "Hvilken planet har flest kjente måner?", a: "Saturn" },
  { q: "Hva heter Batmans hjemby?", a: "Gotham City" },
  { q: "Hva heter valutaen i Japan?", a: "Yen" },
  { q: "Hvor mange tangenter har et vanlig piano?", a: "88" },
  { q: "Hva heter den norske kongen?", a: "Harald V" },
  { q: "Hvilket dyr er størst: elefant eller blåhval?", a: "Blåhval" },
  { q: "Hva heter Supermanns hjemplanet?", a: "Krypton" },
  { q: "Hvor mange timer er det i en uke?", a: "168" },
  { q: "Hva er hovedstaden i Tyskland?", a: "Berlin" },
  { q: "Hvilken frukt er kjent som «apple» på engelsk?", a: "Eple" },
  { q: "Hva heter skaperen av Microsoft (mest kjent)?", a: "Bill Gates" },
  { q: "Hvor mange grader er en rett vinkel?", a: "90" },
  { q: "Hva heter snømannen i «Frost»?", a: "Olaf" },
  { q: "Hvilket hav ligger Hawaii i?", a: "Stillehavet" },
  { q: "Hva heter hovedstaden i Finland?", a: "Helsingfors / Helsinki" },
  { q: "Hvor mange hjul har en trehjulssykkel?", a: "3" }
];

// Tenk likt: ex = eksempler bots kan svare (ikke vist for spillerne)
const TENK_PROMPTS = [
  { p: "Skriv en frukt", ex: ["banan", "eple", "appelsin", "jordbær"] },
  { p: "Skriv en middagsrett", ex: ["taco", "pizza", "fiskeboller", "lasagne"] },
  { p: "Skriv en sport", ex: ["fotball", "håndball", "ski", "tennis"] },
  { p: "Skriv en farge", ex: ["blå", "rød", "grønn", "gul"] },
  { p: "Skriv et dyr på gården", ex: ["ku", "gris", "sau", "høne"] },
  { p: "Skriv et land i Europa", ex: ["Sverige", "Danmark", "Spania", "Frankrike"] },
  { p: "Skriv en grønnsak", ex: ["gulrot", "brokkoli", "agurk", "potet"] },
  { p: "Skriv et kroppsorgan", ex: ["hjerte", "lunge", "lever", "hjerne"] },
  { p: "Skriv et pålegg", ex: ["brunost", "leverpostei", "skinke", "syltetøy"] },
  { p: "Skriv en superhelt", ex: ["Spider-Man", "Batman", "Superman", "Iron Man"] },
  { p: "Skriv et kjøretøy", ex: ["bil", "buss", "sykkel", "tog"] },
  { p: "Skriv en norsk by", ex: ["Oslo", "Bergen", "Trondheim", "Stavanger"] },
  { p: "Skriv noe du finner på et kjøkken", ex: ["kjøleskap", "komfyr", "kniv", "kaffetrakter"] },
  { p: "Skriv et musikkinstrument", ex: ["gitar", "piano", "trommer", "fiolin"] },
  { p: "Skriv en pizzatopping", ex: ["ost", "pepperoni", "skinke", "ananas"] },
  { p: "Skriv et vær", ex: ["regn", "sol", "snø", "vind"] },
  { p: "Skriv et yrke", ex: ["lege", "lærer", "politi", "kokk"] },
  { p: "Skriv et kortspill", ex: ["poker", "uno", "kabal", "amerikaner"] },
  { p: "Skriv en årstid eller måned", ex: ["sommer", "vinter", "desember", "juli"] },
  { p: "Skriv et tegneseriedyr", ex: ["Donald", "Mikke", "Garfield", "Snoopy"] },
  { p: "Skriv et brettspill", ex: ["Monopol", "Ludo", "sjakk", "Alias"] },
  { p: "Skriv et klesplagg", ex: ["bukse", "genser", "jakke", "sokker"] },
  { p: "Skriv en snacks", ex: ["potetgull", "popcorn", "nøtter", "sjokolade"] },
  { p: "Skriv noe man tar med på stranden", ex: ["håndkle", "solkrem", "parasoll", "bok"] },
  { p: "Skriv et dyr i havet", ex: ["hval", "hai", "delfin", "fisk"] },
  { p: "Skriv en drikke", ex: ["vann", "cola", "kaffe", "melk"] },
  { p: "Skriv et eventyr", ex: ["Askepott", "Snøhvit", "Rødhette", "De tre bukkene Bruse"] },
  { p: "Skriv en julegave", ex: ["sokker", "bok", "parfyme", "gavekort"] },
  { p: "Skriv et tall mellom 1 og 10", ex: ["7", "3", "5", "10"] },
  { p: "Skriv en ting i en skolesekk", ex: ["matpakke", "bok", "penal", "PC"] },
  { p: "Skriv en planet", ex: ["Mars", "Jorden", "Jupiter", "Saturn"] },
  { p: "Skriv et dessert", ex: ["is", "kake", "pudding", "sjokolademousse"] },
  { p: "Skriv et rom i et hus", ex: ["kjøkken", "stue", "soverom", "bad"] },
  { p: "Skriv et sosialt medium", ex: ["Snapchat", "Instagram", "TikTok", "Facebook"] },
  { p: "Skriv noe som er gult", ex: ["sol", "banan", "sitron", "ost"] }
];

// Estimering: a = fasit, unit vises alltid
const ESTIMATES = [
  { q: "Hvor høyt er Eiffeltårnet (med antenner)?", unit: "meter", a: 330 },
  { q: "Hvor høy er Galdhøpiggen?", unit: "meter over havet", a: 2469 },
  { q: "Hvor mange innbyggere har Norge (2024)?", unit: "millioner", a: 5.5 },
  { q: "Hvor lang er Norges kystlinje medregnet fjorder (uten øyer)?", unit: "km", a: 28953 },
  { q: "Hvor langt er det fra Oslo til Bergen i luftlinje?", unit: "km", a: 305 },
  { q: "Hvor mange land er medlem av FN?", unit: "land", a: 193 },
  { q: "Hvor mange kilometer er det fra Lindesnes til Nordkapp i luftlinje?", unit: "km", a: 1518 },
  { q: "Hvor mange dager bruker Mars på en runde rundt sola?", unit: "dager", a: 687 },
  { q: "Hva er temperaturen på overflaten av sola?", unit: "°C", a: 5500 },
  { q: "Hvor mange tenner har et voksent menneske (med visdomstenner)?", unit: "tenner", a: 32 },
  { q: "Hvor høy er Burj Khalifa?", unit: "meter", a: 828 },
  { q: "Hvor lang er Kinamuren (alle deler, ifølge Kina 2012)?", unit: "km", a: 21196 },
  { q: "Hvor mange kilo veier en voksen afrikansk elefant (hann) omtrent?", unit: "kg", a: 6000 },
  { q: "Hvor fort kan en gepard løpe?", unit: "km/t", a: 110 },
  { q: "Hvor mange stater har USA?", unit: "stater", a: 50 },
  { q: "Hvilket år ble Oslo grunnlagt (tradisjonelt)?", unit: "år", a: 1048 },
  { q: "Hvor dypt er Marianergropen?", unit: "meter", a: 10935 },
  { q: "Hvor langt er det fra jorden til månen?", unit: "km", a: 384400 },
  { q: "Hvor mange sekunder er det i et døgn?", unit: "sekunder", a: 86400 },
  { q: "Hvor mange liter blod har et voksent menneske?", unit: "liter", a: 5 },
  { q: "Hvor mange øyer har Norge (inkl. holmer og skjær, ifølge Kartverket)?", unit: "øyer", a: 239057 },
  { q: "Hvor lang er Mjøsa?", unit: "km", a: 117 },
  { q: "Hvor mange ganger har Lionel Messi vunnet Ballon d'Or (per 2024)?", unit: "ganger", a: 8 },
  { q: "Hvor mange år lever en grønlandshai (eldste målte omtrent)?", unit: "år", a: 400 },
  { q: "Hvor høyt er Mount Everest?", unit: "meter", a: 8849 },
  { q: "Hvor mange mennesker bor det i verden (2024)?", unit: "milliarder", a: 8.1 },
  { q: "Hvor mange kalorier er det i en vanlig banan?", unit: "kcal", a: 105 },
  { q: "Hvor mange liter vann rommer et olympisk svømmebasseng?", unit: "liter", a: 2500000 },
  { q: "Hvor gammel ble Henrik Ibsen?", unit: "år", a: 78 },
  { q: "Hvor lang er en fotballbane i VM (FIFA-standard)?", unit: "meter", a: 105 },
  { q: "Hvor mange kilometer er det rundt jorden ved ekvator?", unit: "km", a: 40075 },
  { q: "Hvor mange episoder har «Friends» totalt?", unit: "episoder", a: 236 },
  { q: "Hvor mange minutter varer filmen «Titanic» (1997)?", unit: "minutter", a: 194 },
  { q: "Hvor mange tangenter har et vanlig piano?", unit: "tangenter", a: 88 },
  { q: "Hvor mange kvadratkilometer er Norge (fastlandet)?", unit: "km²", a: 323802 }
];

// Lokkeduer til «Hvem er hvilket dyr?» (og dyr bots kan skrive)
const ANIMALS = [
  "Elefant", "Sjiraff", "Pingvin", "Kenguru", "Flodhest", "Neshorn", "Løve", "Tiger", "Sebra", "Koala",
  "Panda", "Isbjørn", "Ulv", "Rev", "Elg", "Reinsdyr", "Gaupe", "Grevling", "Ekorn", "Pinnsvin",
  "Delfin", "Hai", "Blekksprut", "Krokodille", "Kamel", "Lama", "Papegøye", "Ugle", "Flamingo", "Struts",
  "Skilpadde", "Frosk", "Bever", "Oter", "Sel", "Hval", "Ape", "Gorilla", "Dovendyr", "Vaskebjørn"
];

// Bildezoom: innebygde bilder (emoji). Egne bilder: se README og assets/bilder/bilder.json
const IMAGES = [
  { emoji: "🐘", answers: ["elefant"] },
  { emoji: "🦒", answers: ["sjiraff", "giraff"] },
  { emoji: "🐧", answers: ["pingvin"] },
  { emoji: "🦓", answers: ["sebra", "zebra"] },
  { emoji: "🦔", answers: ["pinnsvin"] },
  { emoji: "🐙", answers: ["blekksprut", "åttearmet blekksprut"] },
  { emoji: "🦩", answers: ["flamingo"] },
  { emoji: "🐢", answers: ["skilpadde"] },
  { emoji: "🦉", answers: ["ugle"] },
  { emoji: "🐝", answers: ["bie", "humle"] },
  { emoji: "🍕", answers: ["pizza", "pizzastykke"] },
  { emoji: "🍔", answers: ["hamburger", "burger"] },
  { emoji: "🍌", answers: ["banan"] },
  { emoji: "🍓", answers: ["jordbær"] },
  { emoji: "🍩", answers: ["donut", "smultring", "doughnut"] },
  { emoji: "🧀", answers: ["ost"] },
  { emoji: "🥐", answers: ["croissant", "horn"] },
  { emoji: "🌮", answers: ["taco"] },
  { emoji: "🍉", answers: ["vannmelon", "melon"] },
  { emoji: "🥕", answers: ["gulrot"] },
  { emoji: "🎸", answers: ["gitar", "el-gitar"] },
  { emoji: "⏰", answers: ["vekkerklokke", "klokke"] },
  { emoji: "🔑", answers: ["nøkkel"] },
  { emoji: "🚲", answers: ["sykkel"] },
  { emoji: "☂️", answers: ["paraply"] },
  { emoji: "🎈", answers: ["ballong"] },
  { emoji: "💡", answers: ["lyspære", "pære"] },
  { emoji: "🧲", answers: ["magnet"] },
  { emoji: "🪑", answers: ["stol"] },
  { emoji: "🚀", answers: ["rakett", "romskip"] },
  { emoji: "🧸", answers: ["bamse", "teddybjørn", "kosebamse"] },
  { emoji: "🗽", answers: ["frihetsgudinnen", "statue of liberty"] },
  { emoji: "🌋", answers: ["vulkan"] },
  { emoji: "🏰", answers: ["slott", "borg"] },
  { emoji: "🎡", answers: ["pariserhjul", "pariser hjul"] },
  { emoji: "🌈", answers: ["regnbue"] },
  { emoji: "⚓", answers: ["anker"] },
  { emoji: "🎩", answers: ["flosshatt", "hatt"] }
];

module.exports = { LYN_QUESTIONS, TENK_PROMPTS, ESTIMATES, ANIMALS, IMAGES };
